### ISSUE TITLE
Wire Swift compiler doesn't exclude `google.protobuf.*` properly

### ISSUE THREAD

**Issue by kevincianfarini** [square/wire#1928]
When trying to generate swift protos, we were getting a bunch of extra google protos such as `google.protobuf.EnumOption`. We tried to exclude them with the following. 

```groovy
  args = [
    "--proto_path=$protoPath",
    "--swift_out=$swiftOut",
    "--includes=${includedTypes.join(",")}",
    "--excludes=google.protobuf.*"
  ]
```

which did not take. We also tried to exclude them using a manifest file using the experimental manifest feature which also had no effect. 

```yml
wellknowntypes:
  roots:
    - google.protobuf.Duration
  prunes:
    - google.protobuf.*
```

The root happened to be another google protobuf type, but that doesn't matter. This occurs with any root.
