### ISSUE TITLE
[Swift] Wire outputs file at the wrong path when `extend` is used

### ISSUE THREAD

**Issue by dnkoutso** [square/wire#2560]
Given two protos where one depends on the other:

rpc.proto
```
syntax = "proto2";

package squareup.protos.rpc;

message Response {
  optional string something = 1;
}
```

sync.proto
```
syntax = "proto2";

package squareup.protos.sync;

import "rpc/rpc.proto";

enum SyncErrorCode {
  EXPIRED = 1;
  UNAUTHORIZED = 2;
}

message GetResponse {
  optional string name = 1;
  optional SyncErrorCode sync_error_code = 2;
}

extend squareup.protos.rpc.Response {
  optional SyncErrorCode sync_error_code = 3;
}
```

and a simple manifest:

```
---
squareup_protos_rpc:
  roots:
  - squareup.protos.rpc.Response
  prunes:
  - google.protobuf.*
squareup_protos_sync:
  roots:
  - squareup.protos.sync.GetResponse
  - squareup.protos.sync.SyncErrorCode
  dependencies:
  - squareup_protos_rpc
  prunes:
  - google.protobuf.*
```

Because of the presence of `extend` in `sync.proto` Wire gets tripped out and outputs `SyncErrorCode` into an incorrect path:

```
> Task :wire-runtime-swift:generateTestProtos
Writing .Response declared in rpc/rpc.proto to src/test/swift/gen/squareup_protos_rpc (target=Swift)
Writing .SyncErrorCode declared in rpc/sync.proto to src/test/swift/gen/squareup_protos_rpc (target=Swift) <-- wrong path
Writing .GetResponse declared in rpc/sync.proto to src/test/swift/gen/squareup_protos_sync (target=Swift)
```

Removing `extend` from the `sync.proto` outputs `SyncErrorCode` to the correct path `src/test/swift/gen/squareup_protos_sync`.

If you wish to reproduce:

- Check out branch [wire_extend_issue](https://github.com/square/wire/tree/wire_extend_issue)
- Run `./gradlew :generateSwiftTests` and observe output in console.
- Edit `wire-runtime-swift/src/test/proto/rpc/sync.proto` and remove the `extend` part
- Run `./gradlew :generateSwiftTests` again and observe output in console with the different (and correct) path.

Not sure if this bug affects Kotlin/Java, I only verified it happens in Swift.
