### ISSUE TITLE
Poor colour contrast for headers on docs site

### ISSUE THREAD

**Issue by EdricChan03** [square/wire#3015]
When dark theme is enabled, the docs site's headers don't contrast well against the dark background:

![Screenshot of documentation site with dark theme enabled. Note the poor colour contrast of the headers](https://github.com/square/wire/assets/20047125/d8222da3-cbc5-498a-9b72-d11dc6f23615)

From what I can tell, this is from the hard-coded colour in `docs/css/app.css`:

https://github.com/square/wire/blob/0d30c3fac4ea0c8b6df606aa221fadb152cb3df6/docs/css/app.css#L26-L31

**Comment by oldergod** [comment]
Thank you for reporting. Do you have a suggestion?

**Comment by EdricChan03** [comment]
MkDocs applies a `md-color-scheme` data attribute on the `<body>` tag, so this seems to work:

```css
[data-md-color-scheme="slate"] .md-typeset h1, [data-md-color-scheme="slate"] .md-typeset h2, [data-md-color-scheme="slate"] .md-typeset h3, [data-md-color-scheme="slate"] .md-typeset h4 {
  color: unset; /* or a preferable dark mode colour */
}
```

<img width="1280" alt="Screenshot of docs site with modified colours" src="https://github.com/square/wire/assets/20047125/a500cf3b-9022-4948-80a5-2aa13d9d6ac3">
